"""Standalone script: write config/data_manifest.yaml from a manually downloaded data/ tree.

Run after downloading the Duke Research Data Repository record by hand (see
README "Data sources") and placing its contents under ``data/``. Walks every
file under the configured ``data_root``, computes its size and SHA-256, and
writes ``config/data_manifest.yaml`` in the format ``verify_manifest``
expects. Not a Snakemake rule: it operates on a tree the workflow cannot
produce itself, so it is invoked directly (``pixi run manifest-from-data``).
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from nanostamp.manifest import sha256_of


def build_manifest(data_root: Path) -> dict:
    """Compute a ``{"files": [...]}`` manifest for every file under ``data_root``."""
    files = []
    for path in sorted(data_root.rglob("*")):
        if not path.is_file():
            continue
        files.append(
            {
                "path": str(path.relative_to(data_root)),
                "size_bytes": path.stat().st_size,
                "sha256": sha256_of(path),
            }
        )
    return {"files": files}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-root", type=Path, default=Path("data"))
    parser.add_argument("--manifest", type=Path, default=Path("config/data_manifest.yaml"))
    args = parser.parse_args()

    if not args.data_root.is_dir():
        print(f"No directory at {args.data_root}; download the data first (see README).")
        return 1

    manifest = build_manifest(args.data_root)
    if not manifest["files"]:
        print(f"No files found under {args.data_root}; nothing to write.")
        return 1

    header = (
        "# Manifest of files under data/, generated by "
        "`pixi run manifest-from-data` from a manually downloaded copy of the\n"
        '# Duke Research Data Repository record (see README "Data sources").\n'
        "# `pixi run verify_manifest` checks every entry's size and digest.\n\n"
    )
    args.manifest.write_text(header + yaml.dump(manifest, sort_keys=False))
    print(f"Wrote {len(manifest['files'])} file(s) to {args.manifest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
